import { slider1, slider2, slider3, slider4, slider5, slider6, slider7 } from "../assets";

export  const slides = [
    {
      id:1,
      image: slider1,
      name: 'Wolf 1',
      description: 'Description for Slide 1 Description for Slide 1 Description for Slide 1 Description for Slide 1 Description for Slide 1 Description for Slide 1 Description for Slide 1 Description for Slide 1 Description for Slide 1 Description for Slide 1 ',
    },
    {
        id:2,
        image: slider2,
        name: 'Wolf 2',
        description: 'Description for Slide 2 Description for Slide 2 Description for Slide 2 Description for Slide 2 Description for Slide 2',
      },
      {
        id:3,
        image: slider3,
        name: 'Wolf 3',
        description: 'Description for Slide 3 Description for Slide 3 Description for Slide 3',
      }, 
      {
        id:4,
        image: slider4,
        name: 'Wolf 4',
        description: 'Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4',
      },
      {
        id:5,
          image: slider5,
          name: 'Wolf 5',
          description: 'Description for Slide 5 Description for Slide 5 Description for Slide 5 Description for Slide 5',
       },
        {
            id:6,
          image: slider6,
          name: 'Wolf 6',
          description: 'Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 ',
        }, 
        {id:7,
            image: slider7,
            name: 'Wolf 7',
            description: 'Description for Slide 7',
          },
          {
            id:8,
            image: slider1,
            name: 'Wolf 8',
            description: 'Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4',
          },
          {
            id:9,
              image: slider2,
              name: 'Wolf 9',
              description: 'Description for Slide 5 Description for Slide 5 Description for Slide 5 Description for Slide 5',
            },
            {
                id:10,
              image: slider3,
              name: 'Wolf 10',
              description: 'Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 ',
            }, 
            {id:11,
                image: slider4,
                name: 'Wolf 11',
                description: 'Description for Slide 7',
              },
              {
                id:12,
                image: slider5,
                name: 'Wolf 12',
                description: 'Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4',
              },
              {
                id:13,
                  image: slider6,
                  name: 'Wolf 13',
                  description: 'Description for Slide 5 Description for Slide 5 Description for Slide 5 Description for Slide 5',
                },
                {
                    id:14,
                  image: slider7,
                  name: 'Wolf 14',
                  description: 'Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 ',
                }, 
                {id:15,
                    image: slider1,
                    name: 'Wolf 15',
                    description: 'Description for Slide 7',
                  },,
                  {
                      id:16,
                    image: slider2,
                    name: 'Wolf 16',
                    description: 'Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 ',
                  }, 
                  {id:17,
                      image: slider3,
                      name: 'Wolf 17',
                      description: 'Description for Slide 7',
                    },
                    {
                      id:18,
                      image: slider4,
                      name: 'Wolf 18',
                      description: 'Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4',
                    },
                    {
                      id:19,
                        image: slider5,
                        name: 'Wolf 19',
                        description: 'Description for Slide 5 Description for Slide 5 Description for Slide 5 Description for Slide 5',
                      },
                      {
                          id:20,
                        image: slider6,
                        name: 'Wolf 20',
                        description: 'Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 ',
                      }, 
                      {id:21,
                          image: slider7,
                          name: 'Wolf 21',
                          description: 'Description for Slide 7',
                        },  {id:22,
                          image: slider1,
                          name: 'Wolf 11',
                          description: 'Description for Slide 7',
                        },
                        {
                          id:23,
                          image: slider2,
                          name: 'Wolf 12',
                          description: 'Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4',
                        },
                        {
                          id:24,
                            image: slider3,
                            name: 'Wolf 13',
                            description: 'Description for Slide 5 Description for Slide 5 Description for Slide 5 Description for Slide 5',
                          },
                          {
                              id:25,
                            image: slider4,
                            name: 'Wolf 14',
                            description: 'Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 ',
                          }, 
                          {id:26,
                              image: slider5,
                              name: 'Wolf 15',
                              description: 'Description for Slide 7',
                            },,
                            {
                                id:27,
                              image: slider6,
                              name: 'Wolf 16',
                              description: 'Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 ',
                            }, 
                            {id:28,
                                image: slider7,
                                name: 'Wolf 17',
                                description: 'Description for Slide 7',
                              },
                              {
                                id:29,
                                image: slider1,
                                name: 'Wolf 18',
                                description: 'Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4 Description for Slide 4',
                              },
                              {
                                id:30,
                                  image: slider2,
                                  name: 'Wolf 19',
                                  description: 'Description for Slide 5 Description for Slide 5 Description for Slide 5 Description for Slide 5',
                                },
                                {
                                    id:31,
                                  image: slider3,
                                  name: 'Wolf 20',
                                  description: 'Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 Description for Slide 6 ',
                                }, 
                                {id:32,
                                    image: slider4,
                                    name: 'Wolf 21',
                                    description: 'Description for Slide 7',
                                  },
                    
          
        
  ];
  export const navLinks = [
    {id:1, href: "/", label: "Trending" },
    {id:2, href: "/movies", label: 'Movies' },
    {id:3, href: "/tv", label:'Tv' },
    {id:4, href: "/about", label:'About' },


    
]